In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.signal import argrelextrema
from scipy.signal import find_peaks

In [5]:



#Prepare the data of a single spectrum
data_file="./spectral_Data/spectras/spectrum10.pl"
df = pd.read_csv(data_file,sep="   ",header =2,engine='python')
df=df.dropna(1)
df.rename(columns={'#': 'Energy',' Energy':'g1','Unnamed: 2':'g2','Unnamed: 3':'g3'}, inplace=True)

df.head()

FileNotFoundError: [Errno 2] No such file or directory: './spectral_Data/spectras/spectrum10.pl'

In [3]:
#df['max']=df.iloc[argrelextrema(df.g1.values, np.greater_equal, order=5)[0]]['g1']

#finds all peaks which are higher than 10% of the highest peak
df['max']=df.iloc[find_peaks(df.g1.values,height=df.g1.max()*0.05)[0]   ]['g1'].dropna()

print('Minimal height', df.g1.max()*0.1)
print('peaks index:',find_peaks(df.g1.values,height=df.g1.max()*0.1)[0])
print('peaks intensity',df['max'].dropna().to_numpy())
print('peaks Energys', df['Energy'][df['max'].dropna().index].to_numpy())
test_array_energys=df['Energy'][df['max'].dropna().index].to_numpy()


plt.scatter(df.Energy, df['max'], c='g')
plt.plot(df.Energy, df['g1'])


NameError: name 'df' is not defined

In [33]:

df_test=pd.DataFrame(zip(df['Energy'][df['max'].dropna().index],df['max'].dropna()), 
                     columns=["Energy","Intensity"])
df_test_array=[df_test,df_test]

In [34]:
result = pd.concat(df_test_array, keys=['file 1', 'file 2'])
result


#figure out how to add more to this

Energy  Intensity
file 1 0   -0.758   5.206902
       1   -0.690   6.887800
       2   -0.612   3.550715
       3   -0.472   6.731068
       4   -0.406   6.528676
       5   -0.328   2.034453
       6   -0.152   5.865864
       7   -0.068   4.575878
       8   -0.014   3.767152
       9    0.134   6.366303
       10   0.222   4.157548
       11   0.294   3.106192
       12   0.472   5.887754
       13   0.524   4.055435
       14   0.602   5.134707
       15   0.748   7.858334
       16   0.824   2.625045
       17   0.882   4.225285
file 2 0   -0.758   5.206902
       1   -0.690   6.887800
       2   -0.612   3.550715
       3   -0.472   6.731068
       4   -0.406   6.528676
       5   -0.328   2.034453
       6   -0.152   5.865864
       7   -0.068   4.575878
       8   -0.014   3.767152
       9    0.134   6.366303
       10   0.222   4.157548
       11   0.294   3.106192
       12   0.472   5.887754
       13   0.524   4.055435
       14   0.602   5.134707
       15   0.748   7.858334
       16   0.824   2.625045
       17   0.882   4.225285

In [243]:
#complete code with list
df_test_list=[]
data_file_list=["spectrum.pl","spectrum.pl","spectrum.pl"]
for data_file in data_file_list:
    df = pd.read_csv(data_file,sep="   ",header =2,engine='python')
    df=df.dropna(1)
    df.rename(columns={'#': 'Energy',' Energy':'g1','Unnamed: 2':'g2','Unnamed: 3':'g3'}, 
              inplace=True)
    df['max']=df.iloc[find_peaks(df.g1.values,height=df.g1.max()*0.1)[0]   ]['g1'].dropna()

    df_test_list.append(pd.DataFrame(zip(df['Energy'][df['max'].dropna().index],
                                         df['max'].dropna()), 
                                         columns=["Energy","Intensity"]))

    
result = pd.concat(df_test_list, keys=["Test1","Test2","Test3"])


Empty DataFrame
Columns: []
Index: [(Test1, 0), (Test1, 1), (Test1, 2), (Test1, 3), (Test2, 0), (Test2, 1), (Test2, 2), (Test2, 3), (Test3, 0), (Test3, 1), (Test3, 2), (Test3, 3)]

In [13]:
import itertools as it
import numpy as np
#a=np.arange(-0.5,0.5,0.1)
a=[-0.5,0,0.5]

final=np.asarray(list((it.product(a,a,a,a,a,a))))
print(len(final))

729


In [52]:
for i in range(5):
    print(final[i])

[-0.5 -0.5 -0.5 -0.5 -0.5 -0.5]
[-0.5 -0.5 -0.5 -0.5 -0.5  0. ]
[-0.5 -0.5 -0.5 -0.5 -0.5  0.5]
[-0.5 -0.5 -0.5 -0.5  0.  -0.5]
[-0.5 -0.5 -0.5 -0.5  0.   0. ]


In [53]:
inputfile = "input/submit.sh"
for i in range(5):
    outname="input/test/submit"+str(i)+".sh"
    with open(outname,'w') as new_file:
        with open(inputfile, 'r') as old_file:
            line = old_file.read()
            new_file.write(line.replace("runxxx", "run"+str(i)).replace("xyz", "-mnd -D {name} -p k6a1 {} -p k6a2 {} -p k11 {} -p k12 {} -p k9a1 {} -p k9a2 {}".format(name="run"+str(i),*final[i])))