In [115]:
import pandas as pd
import tensorflow as tf
from matplotlib import pyplot as plt
import numpy as np


from tensorflow.keras.layers import LSTM

In [116]:
df_spectra=pd.read_csv("spectrum_energy_intensity.csv",index_col=[0,1])
df_input=pd.read_csv("input_data_table.csv",index_col=0)
df_input.head()


k6a1  k6a2  k11  k12  k9a1  k9a2
0  -0.5  -0.5 -0.5 -0.5  -0.5  -0.5
1  -0.5  -0.5 -0.5 -0.5  -0.5   0.0
2  -0.5  -0.5 -0.5 -0.5  -0.5   0.5
3  -0.5  -0.5 -0.5 -0.5   0.0  -0.5
4  -0.5  -0.5 -0.5 -0.5   0.0   0.0

In [117]:
test3=df_spectra.groupby(level=1).size()[0] #this gives the number of spectra in the dataset
print(test3)

#this works to get a matrix for each spectrum 
test2=df_spectra[df_spectra.index.isin(["spectrum0"],level=0)]["Energy"].to_numpy()
print(test2)

test4=df_input[df_input.index.isin([0],level=0)].to_numpy()[0]
print(test4)

470
[-0.758 -0.69  -0.612 -0.472 -0.406 -0.328 -0.152 -0.068 -0.014  0.134
  0.222  0.294  0.472  0.524  0.602  0.748  0.824  0.882]
[-0.5 -0.5 -0.5 -0.5 -0.5 -0.5]


In [238]:
test_energy=np.zeros(df_spectra.groupby(level=1).size()[0])
#test_energy[1]=np.zeros(4)
for i in range(df_spectra.groupby(level=1).size()[0]):
    
    test_energy[i]=df_spectra["Energy"].to_numpy()
print(test_energy)

ValueError: setting an array element with a sequence.

In [125]:
list_spectra_Energy_array=[]
list_spectra_Intensity_array=[]
list_input=[]
test_list_spectra_Energy_array=[]
test_list_spectra_Intensity_array=[]
test_list_input=[]
#list_k6a1=df_input["k6a1"].to_numpy()
#list_k6a2=df_input["k6a2"].to_numpy()
#list_k11=df_input["k11"].to_numpy()
#list_k12=df_input["k12"].to_numpy()
#list_k9a1=df_input["k9a1"].to_numpy()
#list_k9a2=df_input["k9a2"].to_numpy()
for i in range(df_spectra.groupby(level=1).size()[0]):
    list_spectra_Energy_array.append(df_spectra[df_spectra.index.isin(["spectrum"
                                                                       +str(i)],level=0)]["Energy"].to_numpy())
    list_spectra_Intensity_array.append(df_spectra[df_spectra.index.isin(["spectrum"
                                                                          +str(i)],level=0)]["Intensity"].to_numpy())
    list_input.append(df_input[df_input.index.isin([i],level=0)].to_numpy()[0])
    test_list_spectra_Energy_array.append([1,1,1])
    test_list_spectra_Intensity_array.append([2,2,2])
    test_list_input.append([3,3,3])

#print(list_spectra_Energy_array[0:2])    
#print(list_spectra_Intensity_array[0:2])    


print(len(list_spectra_Energy_array),len(list_spectra_Intensity_array))
list_energy_spectra_pairs=[]
for i in range(len(list_spectra_Energy_array)):
    append_array=np.zeros([len(list_spectra_Intensity_array[i]),2])
    #print(len(append_array))
    for j in range(len(list_spectra_Intensity_array[i])):
        append_array[j,0]=list_spectra_Energy_array[i][j]
        append_array[j,1]=list_spectra_Intensity_array[i][j]
    list_energy_spectra_pairs.append(append_array)

        
print(list_energy_spectra_pairs[0:2])
print(list_input[0:2])





#list_spectra_Energy_array=np.asarray(list_spectra_Energy_array)   
#list_spectra_Intensity_array=np.asarray(list_spectra_Intensity_array)   
#list_input=np.asarray(list_input)   

#list_spectra_Energy_array=[x.tolist() for x in  list_spectra_Energy_array]
#list_spectra_Intensity_array=[x.tolist() for x in  list_spectra_Intensity_array]
#list_input=[x.tolist() for x in  list_input]

470 470
[array([[-0.758     ,  5.20690186],
       [-0.69      ,  6.88780025],
       [-0.612     ,  3.5507148 ],
       [-0.472     ,  6.73106847],
       [-0.406     ,  6.52867583],
       [-0.328     ,  2.03445274],
       [-0.152     ,  5.86586448],
       [-0.068     ,  4.57587849],
       [-0.014     ,  3.76715204],
       [ 0.134     ,  6.36630283],
       [ 0.222     ,  4.15754817],
       [ 0.294     ,  3.10619177],
       [ 0.472     ,  5.88775394],
       [ 0.524     ,  4.05543485],
       [ 0.602     ,  5.1347072 ],
       [ 0.748     ,  7.85833443],
       [ 0.824     ,  2.62504489],
       [ 0.882     ,  4.22528457]]), array([[-0.692     ,  3.74488966],
       [-0.574     , 23.8435403 ],
       [-0.278     ,  2.65115834],
       [-0.048     , 11.0445002 ],
       [ 0.034     , 15.0444894 ],
       [ 0.596     , 11.2537878 ],
       [ 0.658     , 14.8091845 ]])]
[array([-0.5, -0.5, -0.5, -0.5, -0.5, -0.5]), array([-0.5, -0.5, -0.5, -0.5, -0.5,  0. ])]


In [5]:
df_all=pd.DataFrame({'input_data':list_input,'Intensity_Energy':list_spectra_Intensity_array,'Energy':list_spectra_Energy_array})

In [99]:

df_training= df_all.sample(frac=0.8,random_state=10)
df_testing=df_all.drop(df_training.index)


#print(list_spectra_Energy_array)
# array 2d 
#beispiel von phil
xbla=np.zeros([300,6])
for i in range(300):
    for j in range(6):
        if(j<3):
            xbla[i,j]=test_list_spectra_Energy_array[i][j]
        else:
            xbla[i,j]=test_list_spectra_Intensity_array[i][j-3]
            
ybla=np.zeros([300,3])            
for i in range(300):
    ybla[i]=test_list_input[i]  


print(xbla)


[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 ...
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]]


In [239]:
df_testing.head(50)

input_data  \
4     [-0.5, -0.5, -0.5, -0.5, 0.0, 0.0]   
8     [-0.5, -0.5, -0.5, -0.5, 0.5, 0.5]   
11    [-0.5, -0.5, -0.5, 0.0, -0.5, 0.5]   
13     [-0.5, -0.5, -0.5, 0.0, 0.0, 0.0]   
15    [-0.5, -0.5, -0.5, 0.0, 0.5, -0.5]   
16     [-0.5, -0.5, -0.5, 0.0, 0.5, 0.0]   
18   [-0.5, -0.5, -0.5, 0.5, -0.5, -0.5]   
31     [-0.5, -0.5, 0.0, -0.5, 0.0, 0.0]   
33    [-0.5, -0.5, 0.0, -0.5, 0.5, -0.5]   
40      [-0.5, -0.5, 0.0, 0.0, 0.0, 0.0]   
44      [-0.5, -0.5, 0.0, 0.0, 0.5, 0.5]   
54   [-0.5, -0.5, 0.5, -0.5, -0.5, -0.5]   
62     [-0.5, -0.5, 0.5, -0.5, 0.5, 0.5]   
71      [-0.5, -0.5, 0.5, 0.0, 0.5, 0.5]   
73     [-0.5, -0.5, 0.5, 0.5, -0.5, 0.0]   
74     [-0.5, -0.5, 0.5, 0.5, -0.5, 0.5]   
77      [-0.5, -0.5, 0.5, 0.5, 0.0, 0.5]   
85     [-0.5, 0.0, -0.5, -0.5, 0.0, 0.0]   
89     [-0.5, 0.0, -0.5, -0.5, 0.5, 0.5]   
93     [-0.5, 0.0, -0.5, 0.0, 0.0, -0.5]   
94      [-0.5, 0.0, -0.5, 0.0, 0.0, 0.0]   
112     [-0.5, 0.0, 0.0, -0.5, 0.0, 0.0]   
118     [-0.5, 0.0, 0.0, 0.0, -0.5, 0.0]   
122      [-0.5, 0.0, 0.0, 0.0, 0.0, 0.5]   
123     [-0.5, 0.0, 0.0, 0.0, 0.5, -0.5]   
125      [-0.5, 0.0, 0.0, 0.0, 0.5, 0.5]   
133      [-0.5, 0.0, 0.0, 0.5, 0.5, 0.0]   
134      [-0.5, 0.0, 0.0, 0.5, 0.5, 0.5]   
135   [-0.5, 0.0, 0.5, -0.5, -0.5, -0.5]   
140     [-0.5, 0.0, 0.5, -0.5, 0.0, 0.5]   
141    [-0.5, 0.0, 0.5, -0.5, 0.5, -0.5]   
143     [-0.5, 0.0, 0.5, -0.5, 0.5, 0.5]   
145     [-0.5, 0.0, 0.5, 0.0, -0.5, 0.0]   
150     [-0.5, 0.0, 0.5, 0.0, 0.5, -0.5]   
156     [-0.5, 0.0, 0.5, 0.5, 0.0, -0.5]   
158      [-0.5, 0.0, 0.5, 0.5, 0.0, 0.5]   
177    [-0.5, 0.5, -0.5, 0.0, 0.5, -0.5]   
179     [-0.5, 0.5, -0.5, 0.0, 0.5, 0.5]   
182    [-0.5, 0.5, -0.5, 0.5, -0.5, 0.5]   
200     [-0.5, 0.5, 0.0, 0.0, -0.5, 0.5]   
203      [-0.5, 0.5, 0.0, 0.0, 0.0, 0.5]   
216   [-0.5, 0.5, 0.5, -0.5, -0.5, -0.5]   
221     [-0.5, 0.5, 0.5, -0.5, 0.0, 0.5]   
234    [-0.5, 0.5, 0.5, 0.5, -0.5, -0.5]   
239      [-0.5, 0.5, 0.5, 0.5, 0.0, 0.5]   
243  [0.0, -0.5, -0.5, -0.5, -0.5, -0.5]   
246   [0.0, -0.5, -0.5, -0.5, 0.0, -0.5]   
248    [0.0, -0.5, -0.5, -0.5, 0.0, 0.5]   
250    [0.0, -0.5, -0.5, -0.5, 0.5, 0.0]   
256     [0.0, -0.5, -0.5, 0.0, 0.0, 0.0]   

                                      Intensity_Energy  \
4    [3.03383711, 23.8370405, 3.08890517, 10.074627...   
8    [5.2722158, 6.88100251, 3.56389132, 6.79587247...   
11   [4.17958952, 3.79121636, 14.111953, 4.52343482...   
13   [3.42808628, 7.08558468, 7.09597428, 11.852902...   
15   [4.15699915, 3.80134569, 13.9923655, 4.5655966...   
16                            [15.8215918, 57.5723517]   
18   [1.31912689, 5.06947509, 7.00535846, 3.4984428...   
31   [3.44800423, 21.7665112, 2.67183976, 10.826053...   
33   [1.98969652, 1.29104399, 5.84602194, 6.9463655...   
40                [14.8653357, 5.83721849, 51.3530667]   
44   [4.46065287, 4.47722575, 13.994149900000002, 4...   
54   [1.30440384, 5.09069983, 7.01375664, 3.4903106...   
62   [1.31042206, 5.0445575, 6.97390664, 3.5029426,...   
71   [1.76596658, 2.46440117, 2.36095616, 3.1644384...   
73   [3.71015701, 23.8935662, 2.67085324, 11.081068...   
74   [1.93078497, 1.26112829, 5.11227138, 7.1444052...   
77   [1.91946818, 1.29198936, 5.05689562, 7.1868979...   
85                                 [87.96866870000002]   
89   [14.866795000000002, 29.983312899999994, 28.14...   
93   [0.0680699865, 0.0676180606, 0.0687251219, 0.0...   
94                                        [392.963517]   
112                                [78.53412850000002]   
118                                       [388.130549]   
122   [0.0861496715, 0.0708600529, 0.6845479740000001]   
123  [0.0743994813, 0.0752031024, 0.0766513385, 0.0...   
125                          [2.94158159, 0.316680265]   
133                                       [73.6519907]   
134  [14.535286, 29.3356918, 27.4784731, 12.1597374...   
135  [15.0780454, 29.6616402, 26.864988, 12.3091946...   
140  [14.7685811, 29.989818, 26.4713551000000

In [25]:
#create feature column

#I have no idea what i am doing 
feature_columns_A=[]
input_data = tf.feature_column.numeric_column("input")
feature_columns_A.append(input_data)

intensity = tf.feature_column.numeric_column("Intensity")
feature_columns_A.append(intensity)

energy = tf.feature_column.numeric_column("Energy")
feature_columns_A.append(energy)

my_feature_layer_A = tf.keras.layers.DenseFeatures(feature_columns_A)
#this does something

In [231]:
def create_model_new(my_learning_rate,input_shape=[2,10], my_feature_layer=0,unit_layer_1=10,unit_layer_2=12,regulations=0.04):
    """Create and compile a regression model."""
    model = tf.keras.models.Sequential()
    # Add the layer containing the feature columns to the model.
    #model.add(my_feature_layer)

    # Describe the topography of the model by calling the tf.keras.layers.Dense
    # method once for each layer. We've specified the following arguments:
    #   * units specifies the number of nodes in this layer.
    #   * activation specifies the activation function (Rectified Linear Unit).
    #   * name is just a string that can be useful when debugging.
    model.add(LSTM(units=3, input_shape=input_shape))

    # Define the first hidden layer with 10 nodes.   
    #model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(units=unit_layer_1, 
                                  activation='relu', 
                                  kernel_regularizer=tf.keras.regularizers.l1(regulations),
                                  name='Hidden1'))
  
    # Define the second hidden layer with 12 nodes. 
    model.add(tf.keras.layers.Dense(units=unit_layer_2, 
                                  activation='relu', 
                                  kernel_regularizer=tf.keras.regularizers.l1(regulations),
                                  name='Hidden2'))

    # Define the output layer.
    model.add(tf.keras.layers.Dense(units=5,  
                                    name='Output'))                              
  
    model.compile(optimizer=tf.keras.optimizers.Adam(lr=my_learning_rate),
                loss="mean_squared_error",
                metrics=[tf.keras.metrics.MeanSquaredError()])

    return model



In [232]:
def create_model_old(my_learning_rate, my_feature_layer=0,unit_layer_1=10,unit_layer_2=12,regulations=0.04):
    """Create and compile a regression model."""
    model = tf.keras.models.Sequential()
    # Add the layer containing the feature columns to the model.
    #model.add(my_feature_layer)

    # Describe the topography of the model by calling the tf.keras.layers.Dense
    # method once for each layer. We've specified the following arguments:
    #   * units specifies the number of nodes in this layer.
    #   * activation specifies the activation function (Rectified Linear Unit).
    #   * name is just a string that can be useful when debugging.
    model.add(keras.layers.LSTM(units=20, input_shape=(2,10),return_sequences=False))

    # Define the first hidden layer with 10 nodes.   
    
    model.add(tf.keras.layers.Dense(units=unit_layer_1, 
                                  activation='relu', 
                                  kernel_regularizer=tf.keras.regularizers.l1(regulations),
                                  name='Hidden1'))
  
    # Define the second hidden layer with 12 nodes. 
    model.add(tf.keras.layers.Dense(units=unit_layer_2, 
                                  activation='relu', 
                                  kernel_regularizer=tf.keras.regularizers.l1(regulations),
                                  name='Hidden2'))

    # Define the output layer.
    model.add(tf.keras.layers.Dense(units=3,  
                                    name='Output'))                              
  
    model.compile(optimizer=tf.keras.optimizers.Adam(lr=my_learning_rate),
                loss="mean_squared_error",
                metrics=[tf.keras.metrics.MeanSquaredError()])
    model.summary()
    return model



In [233]:
def train_model(model, x_data,y_data, epochs, 
                batch_size=None):
    """Train the model by feeding it data."""
    
    #print(len(dataset))
    # Split the dataset into features and label.
    #features = {name:np.array(value) for name, value in dataset.items()}
   # features_test=[np.array(value) for name, value in dataset.items()]
   # label = np.array(features_test.pop(0))
   # print((features_test))

    #print(label)
   
    #test_tensor=tf.RaggedTensor(features_test,5)
    
    
    
    history = model.fit(x=x_data, y=y_data, batch_size=batch_size,
                      epochs=epochs, shuffle=True) 
    #history = model.fit(x=xbla, y=ybla, batch_size=batch_size,
    #                  epochs=epochs, shuffle=True) 

    # The list of epochs is stored separately from the rest of history.
    epochs = history.epoch
  
    # To track the progression of training, gather a snapshot
    # of the model's mean squared error at each epoch. 
    hist = pd.DataFrame(history.history)
    mse = hist["mean_squared_error"]
    
    return epochs, mse

In [242]:
#start the model
# The following variables are the hyperparameters.
learning_rate = 0.001
epochs = 20
batch_size = 80
#print(list_energy_spectra_pairs[0:2])
#print(list_input[0:2])

#transform lists into 3d array

#for i in range(list_energy_spectra_pairs)
array_of_array_of_spectra_data=np.asarray(list_energy_spectra_pairs)
array_of_array_of_input_data=np.asarray(list_input)
print(array_of_array_of_spectra_data[0:2])
print(array_of_array_of_spectra_data.shape)

print(array_of_array_of_input_data.shape)
print(len(array_of_array_of_spectra_data))
#input_shape=[2,50]

# Specify the label
label_name = "Energy"

# Establish the model's topography.
my_model = create_model_new(learning_rate,input_shape=[2,10])
my_model.summary()

[array([[-0.758     ,  5.20690186],
       [-0.69      ,  6.88780025],
       [-0.612     ,  3.5507148 ],
       [-0.472     ,  6.73106847],
       [-0.406     ,  6.52867583],
       [-0.328     ,  2.03445274],
       [-0.152     ,  5.86586448],
       [-0.068     ,  4.57587849],
       [-0.014     ,  3.76715204],
       [ 0.134     ,  6.36630283],
       [ 0.222     ,  4.15754817],
       [ 0.294     ,  3.10619177],
       [ 0.472     ,  5.88775394],
       [ 0.524     ,  4.05543485],
       [ 0.602     ,  5.1347072 ],
       [ 0.748     ,  7.85833443],
       [ 0.824     ,  2.62504489],
       [ 0.882     ,  4.22528457]])
 array([[-0.692     ,  3.74488966],
       [-0.574     , 23.8435403 ],
       [-0.278     ,  2.65115834],
       [-0.048     , 11.0445002 ],
       [ 0.034     , 15.0444894 ],
       [ 0.596     , 11.2537878 ],
       [ 0.658     , 14.8091845 ]])]
(470,)
(470, 6)
470
Model: "sequential_75"
_________________________________________________________________
Layer (type

In [243]:
epochs, mse = train_model(my_model, list_energy_spectra_pairs,array_of_array_of_input_data, epochs, 
                          batch_size)
plot_the_loss_curve(epochs, mse)

ValueError: Data cardinality is ambiguous:
  x sizes: 18, 7, 21, 21, 7, 21, 21, 7, 19, 20, 2, 9, 9, 6, 9, 9, 2, 20, 20, 7, 21, 21, 7, 21, 21, 7, 19, 20, 7, 22, 23, 7, 23, 22, 7, 20, 9, 2, 9, 10, 3, 10, 9, 2, 9, 20, 7, 21, 23, 7, 23, 22, 7, 20, 20, 7, 21, 21, 7, 21, 21, 7, 20, 20, 2, 9, 9, 6, 9, 9, 2, 20, 18, 7, 21, 21, 7, 21, 21, 7, 17, 6, 1, 6, 6, 1, 6, 6, 1, 6, 3, 1, 6, 7, 1, 7, 6, 1, 3, 7, 1, 6, 6, 1, 6, 6, 1, 7, 6, 1, 6, 6, 1, 6, 6, 1, 6, 2, 1, 6, 3, 1, 3, 6, 1, 2, 6, 1, 6, 6, 1, 6, 6, 1, 6, 7, 1, 6, 6, 1, 6, 6, 1, 7, 3, 1, 6, 7, 1, 7, 6, 1, 3, 6, 1, 6, 6, 1, 6, 6, 1, 6, 21, 7, 22, 21, 7, 21, 20, 7, 21, 9, 2, 9, 10, 2, 10, 9, 2, 9, 20, 7, 21, 23, 7, 23, 21, 7, 20, 21, 7, 23, 21, 7, 21, 23, 7, 21, 10, 2, 9, 9, 2, 9, 9, 2, 9, 21, 7, 23, 21, 7, 21, 23, 7, 22, 20, 7, 21, 23, 7, 23, 21, 7, 20, 9, 2, 9, 10, 2, 10, 9, 2, 9, 21, 7, 21, 21, 7, 21, 21, 7, 21, 21, 7, 18, 19, 7, 19, 20, 7, 21, 9, 2, 10, 10, 2, 10, 10, 2, 9, 20, 7, 21, 23, 7, 23, 21, 7, 21, 19, 7, 22, 22, 7, 22, 22, 7, 18, 10, 2, 10, 9, 2, 9, 10, 2, 10, 18, 7, 22, 22, 7, 22, 22, 7, 18, 20, 7, 21, 23, 7, 23, 21, 7, 19, 9, 2, 10, 10, 2, 10, 10, 2, 9, 21, 7, 19, 19, 7, 19, 19, 7, 21, 8, 1, 6, 6, 1, 6, 9, 1, 8, 10, 1, 3, 10, 3, 10, 3, 1, 13, 7, 1, 6, 6, 1, 6, 6, 1, 7, 6, 1, 6, 7, 1, 7, 6, 1, 6, 3, 1, 1, 5, 1, 5, 1, 1, 3, 6, 1, 6, 7, 1, 7, 6, 1, 6, 7, 1, 6, 6, 1, 6, 6, 1, 7, 9, 1, 4, 10, 3, 10, 5, 1, 14, 8, 1, 8, 6, 1, 6, 6, 1, 8, 21, 7, 19, 19, 7, 19, 19, 7, 21, 9, 2, 10, 10, 2, 10, 10, 2, 9, 21, 7, 21, 23, 7, 23, 21, 7, 20, 18, 7, 22, 22, 7, 22, 22, 7, 19, 10, 2, 10, 9, 2, 9, 10, 2, 10, 18, 7, 22, 22, 7, 22, 22, 7, 19, 22, 7, 21, 23, 7, 23, 21, 7, 21, 9, 2
  y sizes: 470
Please provide data which shares the same first dimension.