In [3]:
import pandas as pd
import numpy as np
from numpy import mean
from numpy import std
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor
import matplotlib.pyplot as plt



from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.svm import SVC

H:\Users\Gwydion\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
H:\Users\Gwydion\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
H:\Users\Gwydion\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
H:\Users\Gwydion\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub

In [4]:
df_spectra=pd.read_csv("spectrum_energy_input_numberOfPeaks.csv",index_col=[0])
x_data=np.asarray([df_spectra["no_of_max"].values]).transpose()
x_data_max=max(x_data)
x_data=x_data/x_data_max
#x_data=np.asarray([df_spectra[["no_of_max","Energy_highest_max_normalized"]].to_numpy()])[0]

y_data=np.asarray([df_spectra[["k6a1","k6a2","k11","k12","k9a1","k9a2"]].to_numpy()])[0]
df_spectra.head(-50)


main_maximum                                         all_maxima  \
0           0.748  [-0.758 -0.69  -0.612 -0.472 -0.406 -0.328 -0....   
1          -0.574               [-0.574 -0.048  0.034  0.596  0.658]   
2           0.732  [-0.928 -0.776 -0.708 -0.628 -0.486 -0.422 -0....   
3           0.734  [-0.926 -0.778 -0.712 -0.628 -0.486 -0.422 -0....   
4          -0.560               [-0.56  -0.03   0.046  0.614  0.674]   
..            ...                                                ...   
674         0.736  [-0.774 -0.706 -0.612 -0.488 -0.424 -0.34  -0....   
675         0.730  [-0.922 -0.776 -0.702 -0.624 -0.49  -0.42  -0....   
676        -0.574               [-0.574 -0.046  0.036  0.594  0.66 ]   
677         0.736  [-0.932 -0.772 -0.736 -0.628 -0.492 -0.424 -0....   
678        -0.702  [-0.932 -0.774 -0.702 -0.628 -0.488 -0.424 -0....   

     no_of_max  k6a1  k6a2   k11   k12  k9a1  k9a2  \
0           18  0.25  0.25  0.25  0.25  0.25  0.25   
1            5  0.25  0.25  0.25  0.25  0.25  0.50   
2           19  0.25  0.25  0.25  0.25  0.25  0.75   
3           19  0.25  0.25  0.25  0.25  0.50  0.25   
4            5  0.25  0.25  0.25  0.25  0.50  0.50   
..         ...   ...   ...   ...   ...   ...   ...   
674         17  0.75  0.75  0.25  0.75  0.75  0.75   
675         19  0.75  0.75  0.50  0.25  0.25  0.25   
676          5  0.75  0.75  0.50  0.25  0.25  0.50   
677         20  0.75  0.75  0.50  0.25  0.25  0.75   
678         21  0.75  0.75  0.50  0.25  0.50  0.25   

     Energy_highest_max_normalized  \
0                            0.874   
1                            0.213   
2                            0.866   
3                            0.867   
4                            0.220   
..                             ...   
674                          0.868   
675                          0.865   
676                          0.213   
677                          0.868   
678                          0.149   

                             Energy_all_max_normalized  
0    [0.121 0.155 0.194 0.264 0.297 0.336 0.424 0.4...  
1                      [0.213 0.476 0.517 0.798 0.829]  
2    [0.036 0.112 0.146 0.186 0.257 0.289 0.33  0.4...  
3    [0.037 0.111 0.144 0.186 0.257 0.289 0.33  0.4...  
4                      [0.22  0.485 0.523 0.807 0.837]  
..                                                 ...  
674  [0.113 0.147 0.194 0.256 0.288 0.33  0.415 0.4...  
675  [0.039 0.112 0.149 0.188 0.255 0.29  0.413 0.4...  
676                    [0.213 0.477 0.518 0.797 0.83 ]  
677  [0.034 0.114 0.132 0.186 0.254 0.288 0.331 0.4...  
678  [0.034 0.113 0.149 0.186 0.256 0.288 0.329 0.4...  

[679 rows x 11 columns]

In [5]:
print(y_data.shape)

print(x_data.shape)


print(y_data)

from sklearn.preprocessing import MultiLabelBinarizer
le = MultiLabelBinarizer()
le.fit(y_data)
y_data_enc=le.transform(y_data)


(729, 6)
(729, 1)
[[0.25 0.25 0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25 0.25 0.5 ]
 [0.25 0.25 0.25 0.25 0.25 0.75]
 ...
 [0.75 0.75 0.75 0.75 0.75 0.25]
 [0.75 0.75 0.75 0.75 0.75 0.5 ]
 [0.75 0.75 0.75 0.75 0.75 0.75]]


In [6]:
#always seems to leave some values at zero
def get_model(n_inputs, n_outputs):
    model = Sequential()
    model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
    #model.add(Dense(25, activation='relu'))
    #model.add(Dense(10, activation='relu'))
    print(n_outputs)
    model.add(Dense(n_outputs, activation='relu'))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

def get_model2(n_inputs, n_outputs):
    model = Sequential()
    model.add(Dense(5, input_dim=n_inputs, kernel_initializer='ones', activation='relu'))
   # model.add(Dense(5, activation='sigmoid'))
   # model.add(Dense(10, activation='sigmoid'))

    #model.add(Dense(10, activation='relu'))
    print(n_outputs)
    model.add(Dense(n_outputs, activation='relu'))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [7]:
def evaluate_model(X, y, epochs):
    results = list()
    n_inputs = X.shape[1]
    print(n_inputs)
    n_outputs = y.shape[1]
    # define evaluation procedure
    cv = RepeatedKFold(n_splits=5, n_repeats=1, random_state=1)
    # enumerate folds
    for train_ix, test_ix in cv.split(X):
        # prepare data
        X_train, X_test = X[train_ix], X[test_ix]
        y_train, y_test = y[train_ix], y[test_ix]
        
       # print(X_train[0],y_train[0])
        #print(len(X_train))
        #print(X_train,y_train)
        # define model
        model = get_model2(n_inputs, n_outputs)
        # fit model
        model.fit(X_train, y_train, verbose=0, epochs=epochs, batch_size=300)
        # make a prediction on the test set
        yhat = model.predict(X_test)
        # round probabilities to class labels
        yhat = yhat
        # calculate accuracy
        
        rse=model.evaluate(X_test,y_test)
        
        #print(y_test,yhat)
        
        
        # store result
        #print( rse)
        results.append(rse)
    
    #y_predict1=[yhat[i][0] for i in range(len(yhat))]
   # y_predict2=[yhat[i][1] for i in range(len(yhat))]
   #y_test1=[y_test[i][0] for i in range(len(y_test))]
   # y_test2=[y_test[i][1] for i in range(len(y_test))]
   # print(y_test)
   # print(yhat)
   
    
    df_test=pd.DataFrame(y_test,columns=["k6a1_test","k6a2_test","k11_test","k12_test","k9a1_test","k9a2_test"])
    df_hat=pd.DataFrame(yhat,columns=["k6a1_hat","k6a2_hat","k11_hat","k12_hat","k9a1_hat","k9a2_hat"])
   # df_test=pd.DataFrame(y_test,columns=["NO_test"])
   # df_hat=pd.DataFrame(yhat,columns=["NO_hat"])

    return results,pd.concat([df_test,df_hat], axis=1)




In [9]:
results=[]
epochs_list=[]
complete_range=[]
for i in range(50,150,10):
    complete_range.append(i)


print(complete_range)
#for i in complete_range:#
#    epochs_list.append(i)
#    results.append( evaluate_model(x_data,y_data,epochs_list[-1])[0])

results,compare =evaluate_model(x_data,y_data,50)

[50, 60, 70, 80, 90, 100, 110, 120, 130, 140]
1
6
5/5 [==============================] - 0s 400us/step - loss: 0.1002
6
5/5 [==============================] - 0s 600us/step - loss: 0.1376
6
5/5 [==============================] - 0s 600us/step - loss: 0.1774
6
5/5 [==============================] - 0s 600us/step - loss: 0.1710
6
5/5 [==============================] - 0s 600us/step - loss: 0.1456


In [10]:
#results_avg=[ sum(res)/len(res) for res in results   ]

print(results)
#plt.plot(epochs_list,results_avg)

print('Accuracy: %.3f (%.3f)' % (mean(results), std(results)))
compare.head()

[0.10021853446960449, 0.13756093382835388, 0.17740970849990845, 0.17099402844905853, 0.1455821394920349]
Accuracy: 0.146 (0.027)


k6a1_test  k6a2_test  k11_test  k12_test  k9a1_test  k9a2_test  k6a1_hat  \
0       0.25       0.25      0.25      0.25       0.75       0.50  0.352777   
1       0.25       0.25      0.25      0.50       0.25       0.50  0.285536   
2       0.25       0.25      0.25      0.50       0.75       0.25  0.352777   
3       0.25       0.25      0.25      0.75       0.25       0.75  0.660157   
4       0.25       0.25      0.25      0.75       0.50       0.50  0.352777   

   k6a2_hat   k11_hat  k12_hat  k9a1_hat  k9a2_hat  
0       0.0  0.334833      0.0  0.298936  0.335616  
1       0.0  0.273233      0.0  0.255340  0.283147  
2       0.0  0.334833      0.0  0.298936  0.335616  
3       0.0  0.617640      0.0  0.493671  0.573807  
4       0.0  0.334833      0.0  0.298936  0.335616